apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orion.fullname" . }}
  labels:
    app: {{ include "orion.name" . }}
    chart: {{ include "orion.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "orion.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "orion.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.mongodb.user }}
          args: ["-dbhost", "{{ .Values.mongodb.url }}", "-db", "{{ .Values.mongodb.db }}",
            "-dbuser", "{{ .Values.mongodb.user }}", "-dbpwd {{ .Values.mongodb.pwd }}", "-logLevel", "{{ .Values.logging.level }}"]
          {{- else }}
          args: ["-dbhost", "{{ .Values.mongodb.url }}", "-logLevel", "{{ .Values.logging.level }}"]
          {{- end }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 1026
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
