apiVersion: v1
appVersion: "1.0"
description: An IoT Agent is a FIWARE component used to bridge between MQTT/HTTP+JSON based protocol IoT devices and the FIWARE NGSI standard used in FIWARE.
name: iotagent
version: 0.2.2
