{{- if .Values.services }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-create-services"
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        imagePullPolicy: IfNotPresent
        image: "crs4/init-fiware"
        args:
          - {{ required "services.git_repo is required"  .Values.services.git_repo }}
          - {{ required "services.git_branch is required" .Values.services.git_branch }}
          - {{ required "services.items_path is required"  .Values.services.items_path }}
          - {{ include "iotagent.fullname" . }}:{{ .Values.service.port }}/iot/services
{{- if .Values.services.resources }}
        resources:
{{  .Values.services.resources | toYaml | indent 10 }}
{{- end }}

{{- if .Values.services.env }}
        env:
{{ tpl ( .Values.services.env | toYaml  ) . | indent 10 }}
{{- end }}
{{- end }}
