apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iotagent.fullname" . }}
  labels:
    app: {{ include "iotagent.name" . }}
    chart: {{ include "iotagent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "iotagent.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "iotagent.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - ln -s /data/config.js /opt/iotajson/custom-config.js;
              cd /opt/iotajson;
              bin/iotagent-json custom-config.js
          ports:
            - name: main
              containerPort: 4041
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /data
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-iotagent-configmap


    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
