apiVersion: v1
kind: Service
metadata:
  name: {{ include "iotagent.fullname" . }}
  labels:
    app: {{ include "iotagent.name" . }}
    chart: {{ include "iotagent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: main
      protocol: TCP
      name: main
  selector:
    app: {{ include "iotagent.name" . }}
    release: {{ .Release.Name }}
