apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cron-job.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cron-job.name" . }}
    helm.sh/chart: {{ include "cron-job.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  {{- if .Values.spec.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.spec.concurrencyPolicy }}
  {{- end }}
  {{- if .Values.spec.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.spec.startingDeadlineSeconds }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cron-job-semaphore: {{ .Values.semaphore | default .Chart.Name | quote }}
        spec:
          restartPolicy: OnFailure
          {{- if .Values.configFiles }}
          volumes:
            - name: {{ include "cron-job.fullname" . }}-volume
              configMap:
                name: {{ include "cron-job.fullname" . }}
                items:
                {{- range $i, $file := .Values.configFiles.files }}
                  - key: {{ $file.name | quote }}
                    path: {{ $file.name | quote }}
                {{- end }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ required "a image repository is required" .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- .Values.args | toYaml  | nindent 16 }}
              resources:
                {{- toYaml .Values.resources | nindent 18 }}
              env:
                {{- toYaml .Values.env | nindent 18 }}
              {{- if .Values.configFiles }}
              volumeMounts:
                - name: {{ include "cron-job.fullname" . }}-volume
                  mountPath: {{ .Values.configFiles.configPath | default "/configs/" | quote }}
                  readOnly: true
              {{- end }}
          {{- with .Values.nodeSelector }}
              nodeSelector:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            {{- with .Values.affinity }}
              affinity:
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.tolerations }}
              tolerations:
                {{- toYaml . | nindent 16 }}
            {{- end }}
