apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "drill.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drill.name" . }}
    helm.sh/chart: {{ include "drill.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "drill.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "drill.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          ports:
            - name: http
              containerPort: 8047
              protocol: TCP
{{- if .Values.storage_plugins }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                   while [[ ! -d /tmp/drill/sys.storage_plugins/ ]]; do sleep 2; done;
                   while [[ $(ls -1q /tmp/drill/sys.storage_plugins/ | wc -l) -lt 1 ]]; do sleep 2; done;
 {{- $values := . -}}
{{- range .Values.storage_plugins }}
                    echo '{{ tpl ( .conf | toJson ) $values  }}'  > /tmp/drill/sys.storage_plugins/{{ .filename }}
{{- end }}
{{- end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
