apiVersion: v1
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: {{ .Release.Name }}-flink-jobmanager
{{ .Values.ports | toYaml | indent 4 }}
{{ .Values.conf | toYaml | indent 4 }}

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flink-configmap
  namespace: default
