apiVersion: v1
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: {{ include "flink.fullname" . }}-jobmanager
{{ .Values.conf | toYaml | indent 4 }}

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flink-configmap
  namespace: default
