apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "flink.fullname" . }}-jobmanager
  labels:
    app: {{ include "flink.name" . }}-jobmanager
    chart: {{ include "flink.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flink.name" . }}-jobmanager
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "flink.name" . }}-jobmanager
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- $_ := set .Values "command_arg" "jobmanager" }}
{{ include "flink.command" . | indent 10 }}
          ports:
            - name: web
              containerPort: {{ index .Values.conf "web.port" }}
            - name: rpc
              containerPort: {{ index .Values.conf "jobmanager.rpc.port" }}
            - name: blob
              containerPort: {{ index .Values.conf "blob.server.port" }}
            - name: query
              containerPort: {{ index .Values.conf "query.server.port" }}
            - name: ha
              containerPort: {{ index .Values.conf "high-availability.jobmanager.port" }}
{{- include "flink.env" . | indent 10 }}
{{ include "flink.volumeMounts" . | indent 10 }}
{{ include "flink.volumes" . | indent 6 }}
