apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "flink.fullname" . }}-jobmanager
  labels:
    app: {{ include "flink.name" . }}-jobmanager
    chart: {{ include "flink.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.jobmanager.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flink.name" . }}-jobmanager
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "flink.name" . }}-jobmanager
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- $_ := set .Values "command_arg" "jobmanager" }}
{{ include "flink.command" . | indent 10 }}
          ports:
            - name: web
              containerPort: {{ index .Values.conf "web.port" }}
            - name: rpc
              containerPort: {{ index .Values.conf "jobmanager.rpc.port" }}
            - name: blob
              containerPort: 6124
            - name: query
              containerPort: 6125
            - name: ha
              containerPort: {{ index .Values.conf "high-availability.jobmanager.port" }}
          resources:
            {{- toYaml .Values.jobmanager.resources | nindent 12 }}
          env:
            {{- include "flink.env" . | indent 10 }}
          volumeMounts:
            {{- include "flink.volumeMounts" . | indent 10 }}
      {{- with .Values.jobmanager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.jobmanager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jobmanager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- include "flink.volumes" . | indent 8 }}
