apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "flink.fullname" . }}-taskmanager
  labels:
    app: {{ include "flink.name" . }}-taskmanager
    chart: {{ include "flink.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flink.name" . }}-taskmanager
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "flink.name" . }}-taskmanager
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- $_ := set .Values "command_arg" "taskmanager" }}
{{ include "flink.command" . | indent 10 }}
          ports:
            - name: rpc
              containerPort: {{ index .Values.conf "taskmanager.rpc.port"  }}
            - name: data
              containerPort: {{ index .Values.conf "taskmanager.data.port" }}
{{- include "flink.env" . | indent 10 }}
{{ include "flink.volumeMounts" . | indent 10 }}
{{ include "flink.volumes" . | indent 6 }}
