apiVersion: v1
kind: Service
metadata:
  name: {{ include "flink.fullname" . }}-taskmanager
  labels:
    app: {{ include "flink.name" . }}-taskmanager
    chart: {{ include "flink.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.taskmanager.service }}
  ports:
    - name: rpc
      port: {{ index .Values.ports "taskmanager.rpc.port"  }}
    - name: data
      port: {{ index .Values.ports "taskmanager.data.port" }}

  selector:
    app: {{ include "flink.name" . }}-taskmanager
    release: {{ .Release.Name }}

