apiVersion: v1
data:
  config.py: |
    AUTH_TOKEN = {{ tpl (required "Admin token is required" .Values.conf.adminToken | quote) . }}
    DB_HOST = {{ tpl (required "dbHost is required" .Values.conf.dbHost | quote) . }}
    DB_NAME = {{ tpl (required "dbName is required" .Values.conf.dbName | quote) . }}
    DB_USER = {{ tpl (required "dbUser is required" .Values.conf.dbUser | quote) . }}
    DB_PASSWORD = {{ tpl (required "dbPassword is required" .Values.conf.dbPassword | quote) . }}
    LOG_LEVEL = {{ .Values.conf.logLevel | quote }}
    {{ if .Values.conf.anonymizer_db -}}
    LOC_ANONYMIZER_DB = {{ .Values.conf.anonymizer_db | quote }}
    {{ end }}

{{- with .Values.conf -}}
    {{- if not .internalVfs -}}
      {{- fail "internalVfs configuration is required" -}}
    {{- end }}
    TILEDB_INTERNAL_VFS = {{- include "tdmq.vfsConfig" .internalVfs | indent 4 }}

    {{- if (or (and .externalHostDomain (not .externalVfs)) (and .externalVfs (not .externalHostDomain))) }}
      {{- fail "conf.externalHostDomain and conf.externalVfs must be specified together" -}}
    {{- end -}}

    {{- if .externalHostDomain }}
    EXTERNAL_HOST_DOMAIN = {{ .externalHostDomain | quote }}
    TILEDB_EXTERNAL_VFS = {{- include "tdmq.vfsConfig" .externalVfs | indent 4 }}
    {{- end }}
{{- end }}
kind: ConfigMap
metadata:
  name: {{ include "tdmq.fullname" . }}
