{{- if (include "tdmq.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tdmq.fullname" . }}
  labels:
    app: {{ template "tdmq.name" . }}
    chart: {{ template "tdmq.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  tdmq-admin-token: {{ template "tdmq.adminToken" . }}
{{- end -}}
