apiVersion: v1
name: datacube-db
version: 0.0.1
appVersion: 11.3.0-1
description: Chart for TDM's datacube-db.
keywords:
- datacube-db
- postgresql
- postgres
- database
- sql
- replication
- cluster
